"""Builds supabase/migrations/members.sql from the TLA membership workbook.
Usage: python scripts/build_members_sql.py "<path to xlsx>"
Keeps only paid = yes rows and tidies faculty / department / district spellings."""
import re, sys, openpyxl

SRC = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\mithu\Downloads\TLA Membership 26.xlsx"
OUT = "supabase/migrations/members.sql"

DISTRICT = {
    "amphara": "Ampara", "badullla": "Badulla", "batticalo": "Batticaloa", "batticaloe": "Batticaloa",
    "jkilinochchi": "Kilinochchi", "killinochchi": "Kilinochchi", "killinochi": "Kilinochchi",
    "kalubowila hospital road": "Colombo", "kaluthara": "Kalutara", "kaluthura": "Kalutara",
    "kalutura": "Kalutara", "krunagela": "Kurunegala", "kurunagale": "Kurunegala",
    "kurunagela": "Kurunegala", "matala": "Matale", "mullaitheevu": "Mullaitivu",
    "mullaithevu": "Mullaitivu", "mullaithivu": "Mullaitivu", "negambo": "Gampaha",
    "nuvaraeliyaa": "Nuwara Eliya", "nuwara-eliya": "Nuwara Eliya", "nuwaraeliya": "Nuwara Eliya",
    "nuwareliya": "Nuwara Eliya", "nuwera eliya": "Nuwara Eliya", "nuweraeliya": "Nuwara Eliya",
    "nuweraliya": "Nuwara Eliya", "nuwereliya": "Nuwara Eliya",
}
FACULTY = {"enigineering": "Engineering", "engoneering": "Engineering", "it": "IT"}
DEPT = {
    "cse": "Computer Science & Engineering", "computer science": "Computer Science & Engineering",
    "it": "Information Technology", "itm": "Information Technology & Management",
    "ce": "Civil Engineering", "civil": "Civil Engineering", "civil engineering": "Civil Engineering",
    "me": "Mechanical Engineering", "mechanical": "Mechanical Engineering", "mechanical engineering": "Mechanical Engineering",
    "ee": "Electrical Engineering", "electrical": "Electrical Engineering", "electrical engineering": "Electrical Engineering",
    "entc": "Electronic & Telecommunication Engineering",
    "ere": "Earth Resources Engineering", "cpe": "Chemical & Process Engineering",
    "chemical": "Chemical & Process Engineering", "chemical engineering": "Chemical & Process Engineering",
    "mat": "Materials Science & Engineering", "material engineering": "Materials Science & Engineering",
    "materials science & engineering": "Materials Science & Engineering",
    "bme": "Biomedical Engineering", "biomedical": "Biomedical Engineering",
    "textile and apperal engineering": "Textile & Apparel Engineering", "textile engineering": "Textile & Apparel Engineering",
    "tmle": "Transport Management & Logistics Engineering",
    "qs": "Quantity Surveying", "quantity surveying": "Quantity Surveying",
    "tcp": "Town & Country Planning", "town and country planning": "Town & Country Planning",
    "fm": "Facilities Management", "facilities management": "Facilities Management",
    "landscape": "Landscape Architecture", "landscape architecture": "Landscape Architecture",
    "ids": "Integrated Design", "integrated design": "Integrated Design",
    "building economics": "Building Economics", "architecture": "Architecture",
}

def clean(v):
    return re.sub(r"\s+", " ", str(v)).strip() if v is not None and str(v).strip() not in ("", "None") else None

def col(header):
    h = [(clean(c) or "").lower() for c in header]
    return {k: h.index(k) for k in ("batch", "faculty", "department", "district", "paid")}, (h.index("name") if "name" in h else 0)

rows = []
wb = openpyxl.load_workbook(SRC, data_only=True)
for ws in wb:
    data = list(ws.iter_rows(values_only=True))
    c, n = col(data[0])
    for r in data[1:]:
        name = clean(r[n])
        if not name or (clean(r[c["paid"]]) or "").lower() != "yes":
            continue
        batch = int(float(r[c["batch"]])) if r[c["batch"]] is not None else int(ws.title.strip())
        fac = clean(r[c["faculty"]]); fac = FACULTY.get((fac or "").lower(), fac)
        dep = clean(r[c["department"]]); dep = DEPT.get((dep or "").lower(), dep)
        dis = clean(r[c["district"]]); dis = DISTRICT.get((dis or "").lower(), dis.title() if dis else None)
        rows.append((batch, name, fac, dep, dis))

q = lambda s: "null" if s is None else "'" + s.replace("'", "''") + "'"
vals = ",\n".join(f"  ({b}, {q(n)}, {q(f)}, {q(d)}, {q(s)})" for b, n, f, d, s in rows)
sql = f"""-- Paid TLA members shown on /members, grouped by batch. Generated by
-- scripts/build_members_sql.py from the membership workbook. Run this once in
-- the Supabase SQL Editor (re-running replaces all rows).

create table if not exists public.members (
  id bigint generated always as identity primary key,
  batch smallint not null,
  name text not null,
  faculty text,
  department text,
  district text,
  created_at timestamptz not null default now()
);

create index if not exists members_batch_idx on public.members (batch);

alter table public.members enable row level security;

drop policy if exists "members_public_read" on public.members;
create policy "members_public_read"
  on public.members for select
  using (true);

-- Only signed-in admins (there is no public sign-up — see adminStore.js) can
-- change members.
drop policy if exists "members_admin_write" on public.members;
create policy "members_admin_write"
  on public.members for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

truncate public.members restart identity;

insert into public.members (batch, name, faculty, department, district) values
{vals};
"""
open(OUT, "w", encoding="utf-8").write(sql)
from collections import Counter
print(len(rows), Counter(r[0] for r in rows))
print(sorted({r[4] for r in rows if r[4]}))
print(Counter(r[3] for r in rows).most_common())
